CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    passhash TEXT NOT NULL,
    email TEXT NOT NULL,
    pushover_key TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    keyhash BLOB NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires INTEGER NOT NULL);

CREATE TABLE accept_invites (
    my_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    from_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (my_id, from_id),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE rooms (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE participating_in (
    roomid INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    userid INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (roomid, userid),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE charas (
    id INTEGER PRIMARY KEY,
    roomid INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    nick TEXT NOT NULL,
    color TEXT NOT NULL,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    updated_at TEXT);

CREATE TABLE messages (
    roomid INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    num INTEGER NOT NULL,
    rev INTEGER NOT NULL DEFAULT 0,
    UNIQUE (roomid, num, rev),
    kind TEXT NOT NULL,
    subkind TEXT NULL,
    content TEXT NOT NULL,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
